name: Sergio Freitas
description: "Front-end e Back-end com Cerveja"
meta_description: "Blog sobre desenvolvimento web, e algumas coisas a mais"

markdown: redcarpet
pygments: true
logo: false
paginate: 15
permalink: /blog/:title.html

# Details for the RSS feed generator
url:            'http://sergiofreitas.github.com'
author:         'Sergio Freitas'
